// Übungsdatenbank Kettlebell
// WICHTIG: 'id' einer Übung nie ändern – gespeicherte Trainingsdaten verweisen darauf.
// Neue Übungen (auch ohne Kettlebell) unten per EX.push({...}) ergänzen.
// Felder: id, name, group, level, muscles, volume, steps[], mistake,
//   type ('kettlebell' Standard, später z. B. 'bodyweight' oder 'dumbbell'),
//   kbCount (Anzahl Kettlebells, wird automatisch gesetzt), equip (Text),
//   Animation: stance, kb, kbL, rel, legs, base, keys, period, cam, props (optional).
const GROUPS=['Beine','Po & hintere Kette','Rücken','Brust','Schultern','Arme','Bauch','Rumpf','Ganzkörper'];
const SUP={hinge:-90,hx:0,hy:.14};
const FLOORCAM={x:-.15,y:.4,R:3.3,h:1.1};
const G={wr:-15,sh:0,el:140,inw:0,fin:35};
const AP={RACK:{sh:0,el:149,inw:0,fin:22},HP:{sh:115,el:122,inw:-20,rot:137},UR:{sh:97,el:142,inw:-30,rot:109},CURL:{sh:0,el:127,inw:0,rot:28},TRI:{sh:160,el:147,inw:7,rot:42},WM0:{sh:180,inw:0},WM1:{sh:186,inw:-68},RT:{sh:19,el:112,inw:0,fin:95}};
const EX=[
// ---------- Beine
{id:'goblet-squat',name:'Goblet Squat',group:'Beine',level:'Einsteiger',muscles:'Vordere Oberschenkel, Po, Adduktoren, Bauch',volume:'3 × 8–12',
 steps:['Füße etwas breiter als schulterbreit, Zehen leicht nach außen.','Glocke seitlich am Griff fassen und nah vor der Brust halten.','Tief in die Hocke, bis die Oberschenkel etwa parallel sind. Ellbogen zeigen nach vorne.','Aus den Beinen hochdrücken, Oberkörper bleibt aufrecht.'],
 mistake:'Die Glocke wandert von der Brust weg und der Oberkörper kippt nach vorne.',
 stance:.15,kb:'twoDown',rel:{R:1,L:1},base:{R:G,L:G},period:3.2,
 keys:[{t:0,txt:'Knie und Hüfte gleichzeitig beugen'},{t:.45,p:{hy:.51,hx:-.24,hinge:25},txt:'Unten: Oberschenkel etwa parallel, Brust oben'},{t:.55,p:{hy:.51,hx:-.24,hinge:25},txt:'Aus den Beinen hochdrücken'}]},
{id:'sumo-kniebeuge',name:'Sumo-Kniebeuge',group:'Beine',level:'Einsteiger',muscles:'Adduktoren, vordere Oberschenkel, Po',volume:'3 × 10–15',
 steps:['Sehr breiter Stand, Zehen deutlich nach außen.','Glocke mit beiden Händen am Griff, Arme hängen gestreckt.','Hüfte senkrecht absenken, Knie schieben in Richtung der Zehen nach außen.','Aus den Fersen zurück in den Stand drücken.'],
 mistake:'Die Knie fallen nach innen. Drücke sie aktiv nach außen über die Füße.',
 stance:.27,kb:'twoDown',base:{R:{inw:17.8},L:{inw:17.8}},period:3,
 keys:[{t:0,txt:'Hüfte senkrecht absenken'},{t:.45,p:{hy:.62,hx:-.1,hinge:15},txt:'Unten: Knie zeigen nach außen'},{t:.55,p:{hy:.62,hx:-.1,hinge:15},txt:'Aus den Fersen hochdrücken'}]},
{id:'ausfallschritt-rueckwaerts',name:'Ausfallschritt rückwärts',group:'Beine',level:'Einsteiger',muscles:'Vordere Oberschenkel, Po, hintere Oberschenkel',volume:'3 × 8 pro Bein',
 steps:['Glocke im Goblet-Griff vor der Brust halten.','Mit einem Bein einen großen Schritt nach hinten machen.','Beide Knie beugen, bis das hintere Knie knapp über dem Boden ist.','Über das vordere Bein zurück in den Stand drücken.'],
 mistake:'Das vordere Knie schiebt weit über die Zehen und die Ferse hebt ab.',
 stance:.11,kb:'twoDown',rel:{R:1,L:1},base:{R:G,L:G},period:3.2,
 keys:[{t:0,txt:'Großen Schritt nach hinten machen'},{t:.42,p:{hx:-.2,hy:.55,hinge:5,RF:{fx:-.55,fy:.12,fa:-30}},txt:'Unten: hinteres Knie knapp über dem Boden'},{t:.55,p:{hx:-.2,hy:.55,hinge:5,RF:{fx:-.55,fy:.12,fa:-30}},txt:'Über das vordere Bein hochdrücken'}]},
// ---------- Po & hintere Kette
{id:'kettlebell-swing',name:'Kettlebell Swing',group:'Po & hintere Kette',level:'Einsteiger',muscles:'Po, hintere Oberschenkel, unterer Rücken, Rumpf',volume:'3 × 15',
 steps:['Füße schulterbreit, Glocke ein Stück vor dir.','Hüfte nach hinten schieben und die Glocke zwischen die Beine ziehen.','Hüfte explosiv strecken, die Glocke schwebt mit gestreckten Armen bis Brusthöhe.','Glocke fallen lassen und die Hüfte wieder nach hinten klappen.'],
 mistake:'Aus dem Swing wird eine Kniebeuge oder die Arme heben die Glocke. Die Kraft kommt aus der Hüfte.',
 stance:.12,kb:'two',period:1.8,
 keys:[{t:0,p:{hinge:55,hx:-.2,hy:.81,R:{sh:-30,inw:17.8,el:5},L:{sh:-30,inw:17.8,el:5}},txt:'Hüfte streckt explosiv nach vorne'},
  {t:.5,p:{R:{sh:90,inw:17.8,el:12},L:{sh:90,inw:17.8,el:12}},txt:'Glocke fallen lassen, Hüfte zurück'}]},
{id:'kreuzheben',name:'Kreuzheben',group:'Po & hintere Kette',level:'Einsteiger',muscles:'Po, hintere Oberschenkel, Rückenstrecker',volume:'3 × 8–10',
 steps:['Füße schulterbreit, Glocke mittig zwischen den Füßen.','Hüfte nach hinten schieben, Knie beugen, Griff mit beiden Händen fassen.','Schultern zurück, Bauch und Rücken anspannen.','Über Beine und Hüfte aufrichten, dann kontrolliert absetzen.'],
 mistake:'Ein runder unterer Rücken. Stelle die Glocke notfalls auf eine Erhöhung.',
 stance:.12,kb:'twoDown',base:{R:{inw:17.8},L:{inw:17.8}},period:3,
 keys:[{t:0,txt:'Hüfte nach hinten, Glocke absenken'},{t:.4,p:{hinge:50,hx:-.28,hy:.57},txt:'Unten: Rücken gerade, Schultern zurück'},{t:.55,p:{hinge:50,hx:-.28,hy:.57},txt:'Füße in den Boden drücken, aufrichten'}]},
{id:'einbeiniges-kreuzheben',name:'Einbeiniges Kreuzheben',group:'Po & hintere Kette',level:'Mittel',muscles:'Po, hintere Oberschenkel, Gleichgewicht',volume:'3 × 8 pro Bein',
 steps:['Glocke in einer Hand, auf dem gegenüberliegenden Bein stehen.','Standbein leicht gebeugt, Oberkörper nach vorne neigen.','Das freie Bein streckt sich nach hinten, Körper bildet eine Linie.','Über den Po des Standbeins wieder aufrichten.'],
 mistake:'Die Hüfte der freien Seite dreht nach oben auf. Beide Hüftknochen zeigen zum Boden.',
 stance:.1,kb:'oneHang',legs:{R:'fk'},base:{L:{inw:-8,el:10}},period:3.4,
 keys:[{t:0,p:{RF:{th:12,kn:-35,fa:0}},txt:'Oberkörper senkt sich, Bein geht nach hinten'},{t:.45,p:{hinge:75,hx:-.12,hy:.88,RF:{th:-75,kn:0,fa:-75}},txt:'Unten: Körper bildet eine Linie'},{t:.58,p:{hinge:75,hx:-.12,hy:.88,RF:{th:-75,kn:0,fa:-75}},txt:'Über das Standbein aufrichten'}]},
{id:'hip-thrust-am-boden',name:'Hip Thrust am Boden',group:'Po & hintere Kette',level:'Einsteiger',muscles:'Po, hintere Oberschenkel',volume:'3 × 12–15',
 steps:['Rückenlage, Knie gebeugt, Füße hüftbreit am Boden.','Glocke auf den Hüften mit beiden Händen festhalten.','Po anspannen und die Hüfte anheben, bis Knie, Hüfte und Schultern eine Linie bilden.','Oben kurz halten und langsam ablegen.'],
 mistake:'Das Hohlkreuz statt des Pos hebt die Hüfte. Rippen unten lassen.',
 stance:.12,kb:'hip',rel:{R:1,L:1},base:Object.assign({},SUP,{R:{sh:33,inw:17},L:{sh:33,inw:17},RF:{fx:.45},LF:{fx:.45}}),period:3,cam:FLOORCAM,
 keys:[{t:0,txt:'Po anspannen, Hüfte anheben'},{t:.42,p:{hinge:-106,hy:.34},txt:'Oben: Knie, Hüfte und Schultern in einer Linie'},{t:.6,p:{hinge:-106,hy:.34},txt:'Langsam ablegen'}]},
{id:'suitcase-kreuzheben',name:'Suitcase-Kreuzheben',group:'Po & hintere Kette',level:'Einsteiger',muscles:'Po, Oberschenkel, seitlicher Rumpf',volume:'3 × 8 pro Seite',
 steps:['Glocke steht seitlich neben einem Fuß.','In die Hocke gehen und den Griff mit einer Hand fassen.','Aufrichten, ohne zur Glockenseite zu kippen.','Kontrolliert absetzen, erst eine Seite komplett.'],
 mistake:'Der Oberkörper neigt sich zur Glocke. Die Schultern bleiben waagerecht.',
 stance:.1,kb:'oneHang',base:{R:{inw:-5},L:{inw:-5}},period:3,
 keys:[{t:0,txt:'In die Hocke gehen, Griff fassen'},{t:.4,p:{hinge:35,hx:-.2,hy:.5},txt:'Unten: Schultern waagerecht'},{t:.55,p:{hinge:35,hx:-.2,hy:.5},txt:'Aufrichten, nicht zur Seite kippen'}]},
// ---------- Rücken
{id:'einarmiges-rudern',name:'Einarmiges Rudern',group:'Rücken',level:'Einsteiger',muscles:'Breiter Rückenmuskel, mittlerer Rücken, Bizeps',volume:'3 × 10 pro Seite',
 steps:['Knie leicht gebeugt, Oberkörper weit vorgeneigt, Rücken flach.','Arm mit der Glocke hängt gestreckt unter der Brust.','Ellbogen nah am Körper zur Hüfte ziehen.','Oben kurz halten, langsam absenken.'],
 mistake:'Der Oberkörper dreht auf und holt Schwung.',
 stance:.12,kb:'oneHang',base:{hinge:50,hx:-.2,hy:.8,L:{sh:15,inw:-3,el:20}},period:2.6,
 keys:[{t:0,txt:'Ellbogen zur Hüfte ziehen'},{t:.45,p:{R:{sh:-70,el:75}},txt:'Oben: Schulterblatt nach hinten'},{t:.6,p:{R:{sh:-70,el:75}},txt:'Langsam absenken'}]},
{id:'beidarmiges-rudern',name:'Beidarmiges Rudern',group:'Rücken',level:'Einsteiger',muscles:'Oberer und mittlerer Rücken, hintere Schultern',volume:'3 × 10–12',
 steps:['Glocke mit beiden Händen am Griff, Oberkörper vorgeneigt.','Rücken flach, Blick zum Boden.','Glocke zum unteren Brustbein ziehen, Ellbogen gehen nach hinten.','Kontrolliert absenken.'],
 mistake:'Der Rücken rundet sich, um die Glocke höher zu ziehen.',
 stance:.12,kb:'twoDown',base:{hinge:45,hx:-.2,hy:.8,R:{inw:17.8},L:{inw:17.8}},period:2.6,
 keys:[{t:0,txt:'Glocke zum Brustbein ziehen'},{t:.45,p:{R:{sh:-55,el:80,inw:17.8,fin:0},L:{sh:-55,el:80,inw:17.8,fin:0}},txt:'Oben: Schulterblätter zusammen'},{t:.6,p:{R:{sh:-55,el:80,inw:17.8,fin:0},L:{sh:-55,el:80,inw:17.8,fin:0}},txt:'Kontrolliert absenken'}]},
{id:'high-pull',name:'High Pull',group:'Rücken',level:'Mittel',muscles:'Oberer Rücken, Trapez, hintere Schultern, Po',volume:'3 × 10',
 steps:['Aus der Hüftbeuge die Glocke mit beiden Händen greifen.','Hüfte kraftvoll strecken.','Den Schwung nutzen und die Glocke mit hohen Ellbogen bis zur Brust ziehen.','Kontrolliert zurück in die Hüftbeuge.'],
 mistake:'Nur aus den Armen ziehen. Der Impuls kommt aus der Hüfte.',
 stance:.12,kb:'twoDown',base:{R:{inw:17.8},L:{inw:17.8}},period:2.4,
 keys:[{t:0,p:{hinge:40,hx:-.18,hy:.82,R:{sh:-5},L:{sh:-5}},txt:'Hüfte strecken, Ellbogen hoch ziehen'},{t:.45,p:{R:'HP',L:'HP'},txt:'Oben: Ellbogen über den Händen'},{t:.58,p:{R:'HP',L:'HP'},txt:'Zurück in die Hüftbeuge'}]},
// ---------- Brust
{id:'floor-press',name:'Floor Press',group:'Brust',level:'Einsteiger',muscles:'Brust, Trizeps, vordere Schulter',volume:'3 × 10 pro Seite',
 steps:['Rückenlage, Knie gebeugt, Glocke in Rack-Haltung über der Brust.','Oberarm liegt schräg neben dem Körper am Boden.','Glocke senkrecht nach oben drücken, bis der Arm gestreckt ist.','Langsam absenken, bis der Oberarm den Boden berührt.'],
 mistake:'Der Ellbogen schlägt hart auf. Senke ab, bis er den Boden nur berührt.',
 stance:.12,kb:'rack',rel:{R:1,L:1},base:Object.assign({},SUP,{L:{sh:15,inw:-45},RF:{fx:.45},LF:{fx:.45}}),period:2.8,cam:FLOORCAM,
 keys:[{t:0,p:{R:{sh:10,inw:-45,el:100}},txt:'Senkrecht nach oben drücken'},{t:.42,p:{R:{sh:90,inw:0,el:0}},txt:'Oben: Arm gestreckt'},{t:.55,p:{R:{sh:90,inw:0,el:0}},txt:'Langsam absenken'}]},
{id:'pullover',name:'Pullover',group:'Brust',level:'Einsteiger',muscles:'Brust, breiter Rückenmuskel, Rumpf',volume:'3 × 10–12',
 steps:['Rückenlage, Knie gebeugt, Glocke mit beiden Händen an den Seiten des Griffs.','Arme fast gestreckt über der Brust.','In einem Bogen hinter den Kopf absenken.','Mit gestreckten Armen zurück über die Brust ziehen.'],
 mistake:'Der untere Rücken hebt vom Boden ab. Bauch anspannen und nur so weit gehen, wie er liegen bleibt.',
 stance:.12,kb:'twoDown',rel:{R:1,L:1},base:Object.assign({},SUP,{R:{sh:90,inw:17.8,el:10},L:{sh:90,inw:17.8,el:10},RF:{fx:.45},LF:{fx:.45}}),period:3,cam:FLOORCAM,
 keys:[{t:0,txt:'Im Bogen hinter den Kopf absenken'},{t:.45,p:{R:{sh:150},L:{sh:150}},txt:'Unten: Dehnung in Brust und Rücken'},{t:.55,p:{R:{sh:150},L:{sh:150}},txt:'Zurück über die Brust ziehen'}]},
// ---------- Schultern
{id:'ueberkopfdruecken',name:'Überkopfdrücken',group:'Schultern',level:'Mittel',muscles:'Schultern, Trizeps, Rumpf',volume:'3 × 6–8 pro Seite',
 steps:['Glocke in Rack-Position, sie liegt außen am Unterarm.','Bauch und Po anspannen, Rippen über dem Becken.','Senkrecht nach oben drücken, bis der Oberarm neben dem Ohr ist.','Kontrolliert zurück in die Rack-Position.'],
 mistake:'Ins Hohlkreuz zurücklehnen, um die Glocke hochzubekommen.',
 stance:.13,kb:'rack',base:{L:{inw:-8,el:10}},period:3,
 keys:[{t:0,p:{R:'RACK'},txt:'Senkrecht nach oben drücken'},{t:.4,p:{R:{sh:178,el:0,inw:0}},txt:'Oben: Oberarm neben dem Ohr'},{t:.55,p:{R:{sh:178,el:0,inw:0}},txt:'Zurück in die Rack-Position'}]},
{id:'frontheben',name:'Frontheben',group:'Schultern',level:'Einsteiger',muscles:'Vordere Schultern, oberer Rücken',volume:'3 × 10–12',
 steps:['Glocke mit beiden Händen am Griff vor den Oberschenkeln.','Arme fast gestreckt.','Glocke bis auf Schulterhöhe heben.','Langsam absenken, ohne Schwung aus dem Rücken.'],
 mistake:'Mit dem Oberkörper nach hinten schwingen, um die Glocke hochzubringen.',
 stance:.1,kb:'twoDown',base:{R:{inw:17.8,el:5},L:{inw:17.8,el:5}},period:2.8,
 keys:[{t:0,txt:'Bis auf Schulterhöhe heben'},{t:.45,p:{R:{sh:90},L:{sh:90}},txt:'Oben: Arme waagerecht'},{t:.55,p:{R:{sh:90},L:{sh:90}},txt:'Langsam absenken'}]},
{id:'seitheben',name:'Seitheben',group:'Schultern',level:'Einsteiger',muscles:'Seitliche Schulter',volume:'3 × 10 pro Seite',
 steps:['Glocke in einer Hand neben dem Oberschenkel.','Ellbogen minimal gebeugt.','Arm seitlich bis auf Schulterhöhe anheben.','Langsam absenken.'],
 mistake:'Zu schweres Gewicht und Hochziehen der Schulter zum Ohr.',
 stance:.1,kb:'oneDown',base:{R:{inw:-3,el:10},L:{inw:-5}},period:2.8,cam:{az:1.2},
 keys:[{t:0,txt:'Arm seitlich anheben'},{t:.45,p:{R:{inw:-85}},txt:'Oben: Arm auf Schulterhöhe'},{t:.55,p:{R:{inw:-85}},txt:'Langsam absenken'}]},
{id:'aufrechtes-rudern',name:'Aufrechtes Rudern',group:'Schultern',level:'Mittel',muscles:'Seitliche Schultern, Trapez',volume:'3 × 10',
 steps:['Glocke mit beiden Händen eng am Griff vor den Oberschenkeln.','Glocke dicht am Körper nach oben ziehen.','Ellbogen führen und gehen seitlich nach oben.','Unter dem Kinn kurz halten, dann absenken.'],
 mistake:'Zu hoch ziehen, bis es in der Schulter zwickt. Brusthöhe reicht.',
 stance:.1,kb:'twoDown',base:{R:{inw:17.8},L:{inw:17.8}},period:2.8,cam:{az:1.0},
 keys:[{t:0,txt:'Ellbogen führen nach oben'},{t:.45,p:{R:'UR',L:'UR'},txt:'Oben: Ellbogen höher als die Hände'},{t:.55,p:{R:'UR',L:'UR'},txt:'Langsam absenken'}]},
// ---------- Arme
{id:'bizepscurl',name:'Bizepscurl',group:'Arme',level:'Einsteiger',muscles:'Bizeps, Unterarme',volume:'3 × 10–12',
 steps:['Glocke an den Seiten des Griffs halten, Arme gestreckt.','Oberarme bleiben am Körper.','Glocke bis vor die Brust beugen.','Langsam wieder strecken.'],
 mistake:'Schwung aus der Hüfte holen und die Ellbogen nach vorne schieben.',
 stance:.1,kb:'twoDown',base:{R:{inw:14,el:5,rot:28},L:{inw:14,el:5,rot:28}},period:2.6,
 keys:[{t:0,txt:'Glocke zur Brust beugen'},{t:.45,p:{R:'CURL',L:'CURL'},txt:'Oben: Oberarme bleiben ruhig'},{t:.55,p:{R:'CURL',L:'CURL'},txt:'Langsam strecken'}]},
{id:'trizepsdruecken-ueber-kopf',name:'Trizepsdrücken über Kopf',group:'Arme',level:'Einsteiger',muscles:'Trizeps',volume:'3 × 10–12',
 steps:['Glocke mit beiden Händen an den Seiten des Griffs über den Kopf nehmen.','Oberarme bleiben neben den Ohren.','Glocke hinter dem Kopf absenken.','Arme wieder strecken.'],
 mistake:'Die Ellbogen gehen weit auseinander.',
 stance:.12,kb:'twoDown',rel:{R:1,L:1},period:2.8,
 keys:[{t:0,p:{R:'TRI',L:'TRI'},txt:'Arme nach oben strecken'},{t:.45,p:{R:{sh:172,inw:8,el:5,rot:30},L:{sh:172,inw:8,el:5,rot:30}},txt:'Oben: Arme gestreckt'},{t:.55,p:{R:{sh:172,inw:8,el:5,rot:30},L:{sh:172,inw:8,el:5,rot:30}},txt:'Hinter dem Kopf absenken'}]},
// ---------- Rumpf
{id:'russian-twist',name:'Russian Twist',group:'Bauch',level:'Mittel',muscles:'Schräge Bauchmuskeln, gerader Bauch',volume:'3 × 10 pro Seite',
 steps:['Sitzen, Knie gebeugt, Oberkörper gerade nach hinten lehnen.','Füße leicht vom Boden anheben.','Glocke vor der Brust halten und den Oberkörper zur Seite drehen.','Zur anderen Seite drehen, Becken bleibt ruhig.'],
 mistake:'Nur die Arme schwingen. Die Drehung kommt aus dem Oberkörper.',
 stance:.1,kb:'twoDown',legs:{R:'fk',L:'fk'},rel:{R:1,L:1},base:{hinge:-45,hx:0,hy:.19,R:'RT',L:'RT',RF:{th:135,kn:-90,fa:20},LF:{th:135,kn:-90,fa:20}},period:2.6,cam:{x:0,y:.45,R:3.2,h:1.1,az:.7},
 keys:[{t:0,p:{tw:-35},txt:'Zur anderen Seite drehen'},{t:.5,p:{tw:35},txt:'Zur anderen Seite drehen'}]},
{id:'seitbeuge',name:'Seitbeuge',group:'Rumpf',level:'Einsteiger',muscles:'Seitlicher Rumpf, quadratischer Lendenmuskel',volume:'3 × 12 pro Seite',
 steps:['Aufrecht stehen, Glocke in einer Hand.','Oberkörper zur Glockenseite neigen.','Mit der gegenüberliegenden Rumpfseite wieder aufrichten.','Nicht nach vorne oder hinten kippen.'],
 mistake:'Der Oberkörper dreht oder beugt sich nach vorne.',
 stance:.12,kb:'oneDown',base:{R:{inw:-3},L:{inw:-3}},period:3,cam:{az:1.25},
 keys:[{t:0,txt:'Zur Glockenseite neigen'},{t:.4,p:{lb:22},txt:'Unten: seitliche Dehnung'},{t:.5,p:{lb:22},txt:'Mit der anderen Rumpfseite aufrichten'},{t:.85,p:{lb:-6},txt:'Aufrecht'}]},
{id:'windmuehle',name:'Windmühle',group:'Rumpf',level:'Fortgeschritten',muscles:'Schräge Bauchmuskeln, Schulterstabilität, hintere Oberschenkel',volume:'3 × 5 pro Seite',
 steps:['Glocke über Kopf, Füße 45° von der Glocke weg gedreht.','Blick zur Glocke, Arm bleibt senkrecht.','Hüfte zur Glockenseite schieben und den Oberkörper absenken.','Freie Hand gleitet am Bein nach unten, dann zurück.'],
 mistake:'Der Glockenarm kippt aus der Senkrechten. Er zeigt immer zur Decke.',
 stance:.16,kb:'rack',base:{L:{inw:-5}},period:4,cam:{az:1.0,y:1.0},
 keys:[{t:0,p:{R:'WM0'},txt:'Hüfte zur Glockenseite schieben, absenken'},{t:.45,p:{hinge:35,lb:-30,tw:-25,hx:-.08,hz:.06,hy:.9,R:'WM1'},txt:'Unten: Arm zeigt zur Decke'},{t:.6,p:{hinge:35,lb:-30,tw:-25,hx:-.08,hz:.06,hy:.9,R:'WM1'},txt:'Langsam aufrichten'}]},
{id:'dead-bug',name:'Dead Bug',group:'Bauch',level:'Einsteiger',muscles:'Tiefe Bauchmuskeln, gerader Bauch',volume:'3 × 8 pro Seite',
 steps:['Rückenlage, Glocke mit gestreckten Armen über der Brust.','Hüfte und Knie im rechten Winkel.','Ein Bein langsam strecken, bis es knapp über dem Boden ist.','Zurückholen und die Seite wechseln.'],
 mistake:'Der untere Rücken hebt ab. Er bleibt die ganze Zeit am Boden.',
 stance:.1,kb:'two',legs:{R:'fk',L:'fk'},rel:{R:1,L:1},base:Object.assign({},SUP,{R:{sh:90,inw:17.8},L:{sh:90,inw:17.8},RF:{th:180,kn:-90,fa:90},LF:{th:180,kn:-90,fa:90}}),period:4,cam:FLOORCAM,
 keys:[{t:0,txt:'Rechtes Bein strecken'},{t:.25,p:{RF:{th:100,kn:-10,fa:90}},txt:'Zurück in den rechten Winkel'},{t:.5,txt:'Linkes Bein strecken'},{t:.75,p:{LF:{th:100,kn:-10,fa:90}},txt:'Zurück in den rechten Winkel'}]},
// ---------- Ganzkörper
{id:'clean',name:'Clean',group:'Ganzkörper',level:'Mittel',muscles:'Po, hintere Oberschenkel, Rücken, Schultern',volume:'3 × 6 pro Seite',
 steps:['Glocke wie beim Swing zwischen die Beine zurückziehen.','Hüfte explosiv strecken, Ellbogen bleibt nah am Körper.','Die Glocke rollt um die Hand und landet sanft in der Rack-Position.','Zurück zwischen die Beine fallen lassen.'],
 mistake:'Die Glocke schlägt auf den Unterarm. Hand früh um den Griff führen.',
 stance:.12,kb:'oneHang',kb2:'rack',base:{L:{inw:-8,el:10}},period:2.6,
 keys:[{t:0,p:{hinge:50,hx:-.2,hy:.82,R:{sh:-30,inw:10},kbw:0},txt:'Hüfte explosiv strecken'},{t:.3,p:{R:{sh:40,inw:15,el:70},kbw:.3},txt:'Hand um den Griff führen'},{t:.42,p:{R:'RACK',kbw:1},txt:'Rack-Position: Glocke liegt am Unterarm'},{t:.65,p:{R:'RACK',kbw:1},txt:'Zurück zwischen die Beine fallen lassen'}]},
{id:'snatch',name:'Snatch',group:'Ganzkörper',level:'Fortgeschritten',muscles:'Po, hintere Oberschenkel, Schultern, Rumpf',volume:'3 × 5 pro Seite',
 steps:['Glocke zwischen die Beine zurückschwingen.','Hüfte explosiv strecken und die Glocke eng am Körper hochziehen.','Hand um den Griff führen und den Arm über Kopf durchstrecken.','Über den Schwung zurück zwischen die Beine.'],
 mistake:'Die Glocke in einem weiten Bogen nach oben schwingen und hart auf den Unterarm fallen lassen.',
 stance:.12,kb:'oneHang',kb2:'rack',base:{L:{inw:-8,el:10}},period:2.8,
 keys:[{t:0,p:{hinge:50,hx:-.2,hy:.82,R:{sh:-30,inw:10},kbw:0},txt:'Hüfte strecken, Glocke eng hochziehen'},{t:.3,p:{R:{sh:70,inw:10,el:70},kbw:.2},txt:'Hand durchstecken'},{t:.45,p:{R:{sh:178,el:0,inw:0},kbw:1},txt:'Oben: Arm gestreckt über Kopf'},{t:.62,p:{R:{sh:178,el:0,inw:0},kbw:1},txt:'Zurück in den Schwung'}]},
{id:'thruster',name:'Thruster',group:'Ganzkörper',level:'Mittel',muscles:'Beine, Po, Schultern, Trizeps',volume:'3 × 8 pro Seite',
 steps:['Glocke in Rack-Position, schulterbreiter Stand.','Tief in die Kniebeuge gehen.','Explosiv aufstehen und den Schwung direkt ins Überkopfdrücken leiten.','Glocke zurück in die Rack-Position und die nächste Kniebeuge.'],
 mistake:'Erst stehen, dann drücken. Aufstehen und Drücken sind eine fließende Bewegung.',
 stance:.14,kb:'rack',base:{L:{sh:10,inw:-25,el:10}},period:3.4,
 keys:[{t:0,p:{R:'RACK'},txt:'In die Kniebeuge'},{t:.3,p:{hy:.55,hx:-.22,hinge:20,R:'RACK'},txt:'Explosiv hoch und drücken'},{t:.36,p:{hy:.55,hx:-.22,hinge:20,R:'RACK'},txt:'Explosiv hoch und drücken'},{t:.65,p:{R:{sh:178,el:0,inw:0}},txt:'Oben: Arm gestreckt'},{t:.78,p:{R:{sh:178,el:0,inw:0}},txt:'Zurück in die Rack-Position'}]}
];
function resAP(o){if(!o)return;for(const s of ['R','L'])if(typeof o[s]==='string')o[s]=Object.assign({},AP[o[s]]);}
EX.forEach(e=>{resAP(e.base);e.keys.forEach(k=>resAP(k.p));});

const AP2={H0R:{sh:38,inw:10,el:125,rot:28},H2R:{sh:185,inw:-13,el:128,rot:41},H1R:{sh:34,inw:-76,el:145,rot:-49},H1L:{sh:122,inw:53,el:75,rot:50},SKB:{sh:90,el:74,inw:0,rot:25},TG1:{sh:-70,inw:-33,el:77},TG2:{sh:-68,inw:-27,el:38},TG3:{sh:-59,inw:-18,el:21},H0L:{sh:38,inw:10,el:125,rot:28},H2L:{sh:185,inw:-13,el:128,rot:41},H3R:{sh:122,inw:53,el:75,rot:50},H3L:{sh:34,inw:-76,el:145,rot:-49},SQB:{sh:30,el:110,inw:0,rot:30}};
Object.assign(AP,AP2);
EX.push(
{id:'einarmige-frontkniebeuge',name:'Einarmige Frontkniebeuge',group:'Beine',level:'Mittel',muscles:'Vordere Oberschenkel, Po, seitlicher Rumpf',volume:'3 × 8 pro Seite',
 steps:['Glocke in Rack-Position auf einer Seite.','Füße schulterbreit, Bauch fest anspannen.','Tief in die Kniebeuge gehen, ohne zur Glockenseite zu kippen.','Aus den Beinen hochdrücken.'],
 mistake:'Der Oberkörper neigt sich zur Seite mit der Glocke.',
 stance:.15,kb:'rack',base:{R:AP.RACK,L:{sh:10,inw:-25,el:10}},period:3.2,
 keys:[{t:0,txt:'Knie und Hüfte gleichzeitig beugen'},{t:.45,p:{hy:.53,hx:-.23,hinge:22},txt:'Unten: Oberkörper aufrecht'},{t:.55,p:{hy:.53,hx:-.23,hinge:22},txt:'Aus den Beinen hochdrücken'}]},
{id:'seitlicher-ausfallschritt',name:'Seitlicher Ausfallschritt',group:'Beine',level:'Mittel',muscles:'Adduktoren, vordere Oberschenkel, Po',volume:'3 × 8 pro Seite',
 steps:['Glocke im Goblet-Griff vor der Brust.','Großen Schritt zur Seite machen.','Hüfte nach hinten auf das gebeugte Bein setzen, das andere Bein bleibt gestreckt.','Kraftvoll zurück in die Mitte drücken.'],
 mistake:'Das Knie des Schrittbeins fällt nach innen. Es zeigt in Richtung der Zehen.',
 stance:.12,kb:'twoDown',rel:{R:1,L:1},base:{R:G,L:G},period:3.4,cam:{az:1.1},
 keys:[{t:0,txt:'Großen Schritt zur Seite'},{t:.42,p:{hz:.2,hy:.62,hx:-.15,hinge:30,RF:{fz:.62}},txt:'Unten: Hüfte hinten, anderes Bein gestreckt'},{t:.55,p:{hz:.2,hy:.62,hx:-.15,hinge:30,RF:{fz:.62}},txt:'Zurück in die Mitte drücken'}]},
{id:'wadenheben',name:'Wadenheben',group:'Beine',level:'Einsteiger',muscles:'Waden',volume:'3 × 15–20',
 steps:['Aufrecht stehen, Glocke vor der Brust.','Auf die Fußballen hochdrücken.','Oben kurz halten.','Langsam wieder absenken.'],
 mistake:'Zu schnell wippen. Die Bewegung bleibt langsam und kontrolliert.',
 stance:.1,kb:'twoDown',rel:{R:1,L:1},base:{R:G,L:G},period:2.2,
 keys:[{t:0,txt:'Auf die Fußballen hochdrücken'},{t:.4,p:{hy:1.02,RF:{fy:.14,fa:-28},LF:{fy:.14,fa:-28}},txt:'Oben kurz halten'},{t:.55,p:{hy:1.02,RF:{fy:.14,fa:-28},LF:{fy:.14,fa:-28}},txt:'Langsam absenken'}]},
{id:'ueberkopf-kniebeuge',name:'Überkopf-Kniebeuge',group:'Beine',level:'Fortgeschritten',muscles:'Beine, Po, Schulterstabilität, Rumpf',volume:'3 × 5 pro Seite',
 steps:['Glocke mit gestrecktem Arm über Kopf halten.','Füße etwas breiter als schulterbreit.','In die Kniebeuge gehen, der Arm bleibt senkrecht über der Schulter.','Kontrolliert aufstehen.'],
 mistake:'Der Arm kippt nach vorne. Nur so tief gehen, wie er senkrecht bleibt.',
 stance:.16,kb:'rack',base:{R:{sh:180},L:{sh:10,inw:-30,el:10}},period:3.6,
 keys:[{t:0,txt:'Langsam in die Kniebeuge'},{t:.45,p:{hy:.56,hx:-.22,hinge:18},txt:'Unten: Arm senkrecht'},{t:.55,p:{hy:.56,hx:-.22,hinge:18},txt:'Kontrolliert aufstehen'}]},
{id:'einarmiger-swing',name:'Einarmiger Swing',group:'Po & hintere Kette',level:'Mittel',muscles:'Po, hintere Oberschenkel, Rumpf, Griffkraft',volume:'3 × 10 pro Seite',
 steps:['Glocke mit einer Hand greifen, der freie Arm hängt locker.','Wie beim beidarmigen Swing die Hüfte zurückschieben.','Hüfte explosiv strecken, die Glocke schwebt auf Brusthöhe.','Den Oberkörper nicht zur Glocke mitdrehen lassen.'],
 mistake:'Die Schulter der Glockenseite wird nach vorne gezogen. Sie bleibt hinten.',
 stance:.12,kb:'oneHang',period:1.8,
 keys:[{t:0,p:{hinge:55,hx:-.2,hy:.81,R:{sh:-30,inw:10,el:5},L:{sh:-10,inw:-10,el:15}},txt:'Hüfte streckt explosiv nach vorne'},{t:.5,p:{R:{sh:90,inw:10,el:10},L:{sh:10,inw:-10,el:15}},txt:'Glocke fallen lassen, Hüfte zurück'}]},
{id:'good-morning',name:'Good Morning',group:'Po & hintere Kette',level:'Mittel',muscles:'Hintere Oberschenkel, Po, Rückenstrecker',volume:'3 × 10',
 steps:['Glocke vor der Brust halten, Knie leicht gebeugt.','Hüfte weit nach hinten schieben, Rücken bleibt gerade.','Oberkörper absenken, bis die hinteren Oberschenkel dehnen.','Über die Hüfte aufrichten.'],
 mistake:'Aus der Hüftbeuge wird eine Kniebeuge oder der Rücken rundet sich.',
 stance:.12,kb:'twoDown',rel:{R:1,L:1},base:{R:G,L:G},period:3,
 keys:[{t:0,txt:'Hüfte nach hinten schieben'},{t:.42,p:{hinge:70,hx:-.2,hy:.88},txt:'Unten: Dehnung hinten im Oberschenkel'},{t:.55,p:{hinge:70,hx:-.2,hy:.88},txt:'Über die Hüfte aufrichten'}]},
{id:'vorgebeugtes-seitheben',name:'Vorgebeugtes Seitheben',group:'Rücken',level:'Einsteiger',muscles:'Hintere Schultern, oberer Rücken',volume:'3 × 12 pro Seite',
 steps:['Oberkörper weit vorneigen, Knie leicht gebeugt.','Glocke hängt unter der Schulter.','Arm mit leicht gebeugtem Ellbogen seitlich anheben.','Langsam absenken.'],
 mistake:'Mit dem Oberkörper aufdrehen, statt die hintere Schulter arbeiten zu lassen.',
 stance:.12,kb:'oneDown',base:{hinge:55,hx:-.2,hy:.8,R:{el:12},L:{sh:15,inw:-3,el:20}},period:2.8,cam:{az:.9},
 keys:[{t:0,txt:'Arm seitlich anheben'},{t:.45,p:{R:{inw:-80,el:12}},txt:'Oben: Arm auf Rückenhöhe'},{t:.55,p:{R:{inw:-80,el:12}},txt:'Langsam absenken'}]},
{id:'squeeze-press',name:'Squeeze Press',group:'Brust',level:'Einsteiger',muscles:'Brust, Trizeps',volume:'3 × 12',
 steps:['Rückenlage, Glocke mit beiden Händen fest zusammendrücken.','Glocke liegt über der Brust.','Nach oben drücken und dabei weiter fest zusammenpressen.','Langsam zur Brust absenken.'],
 mistake:'Nachlassen beim Zusammendrücken. Der Druck nach innen bleibt die ganze Zeit.',
 stance:.12,kb:'two',rel:{R:1,L:1},base:Object.assign({},SUP,{RF:{fx:.45},LF:{fx:.45}}),period:2.8,cam:FLOORCAM,
 keys:[{t:0,p:{R:AP.SQB,L:AP.SQB},txt:'Nach oben drücken, fest zusammenpressen'},{t:.42,p:{R:{sh:90,inw:17.8},L:{sh:90,inw:17.8}},txt:'Oben: Arme gestreckt'},{t:.55,p:{R:{sh:90,inw:17.8},L:{sh:90,inw:17.8}},txt:'Langsam zur Brust absenken'}]},
{id:'halo',name:'Halo',group:'Schultern',level:'Einsteiger',muscles:'Schultern, oberer Rücken, Rumpf',volume:'3 × 5 pro Richtung',
 steps:['Glocke an den Seiten des Griffs vor der Brust halten.','Glocke eng um den Kopf herumführen.','Hinter dem Kopf den Nacken passieren, Ellbogen zeigen nach oben.','Nach einigen Runden die Richtung wechseln.'],
 mistake:'Der Oberkörper weicht mit aus. Bauch und Po fest, nur die Arme bewegen sich.',
 stance:.12,kb:'twoDown',period:4,cam:{az:.9,y:1.1},
 keys:[{t:0,p:{R:AP.H0R,L:AP.H0L},txt:'Glocke seitlich am Kopf vorbei'},{t:.25,p:{R:AP.H1R,L:AP.H1L},txt:'Hinter den Kopf führen'},{t:.5,p:{R:AP.H2R,L:AP.H2L},txt:'Auf der anderen Seite nach vorne'},{t:.75,p:{R:AP.H3R,L:AP.H3L},txt:'Zurück vor die Brust'}]},
{id:'liegendes-trizepsstrecken',name:'Liegendes Trizepsstrecken',group:'Arme',level:'Einsteiger',muscles:'Trizeps',volume:'3 × 10–12',
 steps:['Rückenlage, Glocke mit beiden Händen über der Brust.','Oberarme zeigen senkrecht nach oben und bleiben ruhig.','Nur die Ellbogen beugen und die Glocke hinter die Stirn absenken.','Arme wieder strecken.'],
 mistake:'Die Oberarme wandern mit. Nur der Unterarm bewegt sich.',
 stance:.12,kb:'twoDown',rel:{R:1,L:1},base:Object.assign({},SUP,{RF:{fx:.45},LF:{fx:.45}}),period:2.8,cam:FLOORCAM,
 keys:[{t:0,p:{R:{sh:90,inw:14,el:5,rot:20},L:{sh:90,inw:14,el:5,rot:20}},txt:'Ellbogen beugen, Glocke hinter die Stirn'},{t:.45,p:{R:AP.SKB,L:AP.SKB},txt:'Unten: Oberarme bleiben ruhig'},{t:.55,p:{R:AP.SKB,L:AP.SKB},txt:'Arme strecken'}]},
{id:'farmer-s-walk',name:"Farmer's Walk",group:'Rumpf',level:'Einsteiger',muscles:'Seitlicher Rumpf, Griffkraft, Trapez',volume:'3 × 30–40 m pro Seite',
 steps:['Glocke in einer Hand neben dem Körper.','Aufrecht stehen, Schultern waagerecht.','Mit kleinen, kontrollierten Schritten gehen.','Nach der Strecke die Hand wechseln.'],
 mistake:'Zur Glockenseite hängen. Der Rumpf hält dagegen und bleibt gerade.',
 stance:.1,kb:'oneDown',base:{hy:.9,R:{inw:-6}},period:1.2,cam:{az:.9},
 keys:[{t:0,p:{RF:{fx:.2},LF:{fx:-.2,fy:.07,fa:-15},L:{sh:-15,inw:-5}},txt:'Aufrecht gehen, Schultern waagerecht'},{t:.25,p:{hy:.92,LF:{fy:.13},L:{sh:0,inw:-5}},txt:'Aufrecht gehen, Schultern waagerecht'},{t:.5,p:{RF:{fx:-.2,fy:.07,fa:-15},LF:{fx:.2},L:{sh:15,inw:-5}},txt:'Rumpf hält gegen die Glocke'},{t:.75,p:{hy:.92,RF:{fy:.13},L:{sh:0,inw:-5}},txt:'Rumpf hält gegen die Glocke'}]},
{id:'clean-press',name:'Clean & Press',group:'Ganzkörper',level:'Mittel',muscles:'Po, hintere Oberschenkel, Schultern, Trizeps',volume:'3 × 5 pro Seite',
 steps:['Glocke aus dem Schwung in die Rack-Position umsetzen.','Kurz stabilisieren, Bauch und Po anspannen.','Senkrecht über Kopf drücken.','Zurück in die Rack-Position und zwischen die Beine fallen lassen.'],
 mistake:'Direkt aus dem Clean drücken, ohne zu stabilisieren, und dabei ins Hohlkreuz fallen.',
 stance:.12,kb:'oneHang',kb2:'rack',base:{L:{inw:-8,el:10}},period:4,
 keys:[{t:0,p:{hinge:50,hx:-.2,hy:.82,R:{sh:-30,inw:10},kbw:0},txt:'Hüfte explosiv strecken'},{t:.2,p:{R:{sh:40,inw:15,el:70},kbw:.3},txt:'In die Rack-Position umsetzen'},{t:.28,p:{R:AP.RACK,kbw:1},txt:'Stabilisieren'},{t:.33,p:{R:AP.RACK,kbw:1},txt:'Senkrecht über Kopf drücken'},{t:.52,p:{R:{sh:178},kbw:1},txt:'Oben: Arm gestreckt'},{t:.6,p:{R:{sh:178},kbw:1},txt:'Zurück in die Rack-Position'},{t:.76,p:{R:AP.RACK,kbw:1},txt:'Zwischen die Beine fallen lassen'}]},
{id:'turkish-get-up',name:'Turkish Get-up',group:'Ganzkörper',level:'Fortgeschritten',muscles:'Ganzer Körper, Schulterstabilität, Rumpf',volume:'3 × 1–2 pro Seite',
 steps:['Rückenlage, Glocke mit gestrecktem Arm über der Brust, Knie auf der Glockenseite gebeugt.','Auf den Ellbogen, dann auf die Hand hochrollen.','Hüfte zur Brücke heben, das gestreckte Bein nach hinten unter den Körper führen und knien.','Aus dem Halbknien aufstehen und den Weg rückwärts zurückgehen.'],
 mistake:'Den Blick von der Glocke nehmen und den Arm aus der Senkrechten kippen lassen.',
 stance:.12,kb:'rack',rel:{L:1},base:{R:{sh:180}},period:14,cam:{x:.1,y:.65,R:4.2,h:1.3,az:.55},
 keys:[
  {t:0,p:{hinge:-90,hy:.14,L:{sh:0,inw:-45},RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Auf den Ellbogen rollen'},
  {t:.1,p:{hinge:-60,hy:.14,L:AP.TG1,RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Auf die Hand hochdrücken'},
  {t:.2,p:{hinge:-35,hy:.14,L:AP.TG2,RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Hüfte zur Brücke anheben'},
  {t:.3,p:{hinge:-50,hy:.3,L:AP.TG3,RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Bein nach hinten durchführen, knien'},
  {t:.42,p:{hinge:-5,hx:.05,hy:.5,L:{sh:0,inw:-10,el:10},RF:{fx:.45,fz:.12},LF:{fx:-.4,fy:.12,fz:-.1,fa:-30}},txt:'Aus dem Halbknien aufstehen'},
  {t:.52,p:{L:{sh:0,inw:-10,el:10}},txt:'Oben: Arm senkrecht, dann rückwärts'},
  {t:.58,p:{L:{sh:0,inw:-10,el:10}},txt:'Zurück ins Halbknien'},
  {t:.66,p:{hinge:-5,hx:.05,hy:.5,L:{sh:0,inw:-10,el:10},RF:{fx:.45,fz:.12},LF:{fx:-.4,fy:.12,fz:-.1,fa:-30}},txt:'Hand aufsetzen, Bein nach vorne führen'},
  {t:.76,p:{hinge:-50,hy:.3,L:AP.TG3,RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Hüfte ablegen'},
  {t:.83,p:{hinge:-35,hy:.14,L:AP.TG2,RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Auf den Ellbogen'},
  {t:.9,p:{hinge:-60,hy:.14,L:AP.TG1,RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Langsam ablegen'},
  {t:.97,p:{hinge:-90,hy:.14,L:{sh:0,inw:-45},RF:{fx:.4,fz:.12},LF:{fx:.85,fz:-.15}},txt:'Rückenlage, Arm senkrecht'}]}
);
EX.push(
{id:'doppelte-frontkniebeuge',name:'Doppelte Frontkniebeuge',group:'Beine',level:'Mittel',muscles:'Vordere Oberschenkel, Po, oberer Rücken, Rumpf',volume:'3 × 6–8',
 steps:['Zwei Glocken in die Rack-Position bringen, Ellbogen nah am Körper.','Füße schulterbreit, Bauch fest anspannen.','Tief in die Kniebeuge gehen, die Brust bleibt oben.','Aus den Beinen hochdrücken.'],
 mistake:'Die Ellbogen sinken ab und der obere Rücken rundet sich unter dem Gewicht.',
 stance:.15,kb:'rack',kbL:'rackL',base:{R:AP.RACK,L:AP.RACK},period:3.2,equip:'2 Kettlebells',
 keys:[{t:0,txt:'Knie und Hüfte gleichzeitig beugen'},{t:.45,p:{hy:.53,hx:-.23,hinge:22},txt:'Unten: Brust oben, Ellbogen vorne'},{t:.55,p:{hy:.53,hx:-.23,hinge:22},txt:'Aus den Beinen hochdrücken'}]},
{id:'step-up',name:'Step-up',group:'Beine',level:'Einsteiger',muscles:'Vordere Oberschenkel, Po',volume:'3 × 8 pro Bein',
 steps:['Vor einen stabilen Kasten stellen, Glocke vor der Brust.','Einen Fuß komplett auf den Kasten setzen.','Über das obere Bein hochdrücken, ohne sich mit dem unteren abzustoßen.','Kontrolliert wieder absteigen.'],
 mistake:'Mit dem unteren Bein Schwung holen. Die Arbeit macht das Bein auf dem Kasten.',
 stance:.1,kb:'twoDown',rel:{R:1,L:1},base:{R:G,L:G},period:4.2,equip:'Kettlebell, Kasten',cam:{x:.25,y:1.05,R:4.4,h:1.4},props:[{x:.5,w:.45,h:.4,d:.6}],
 keys:[{t:0,txt:'Einen Fuß auf den Kasten setzen'},
  {t:.07,p:{hx:.02,hy:.92,RF:{fx:.2,fy:.55}},txt:'Einen Fuß auf den Kasten setzen'},
  {t:.16,p:{hx:.05,hy:.9,hinge:10,RF:{fx:.48,fy:.45}},txt:'Über das obere Bein hochdrücken'},
  {t:.3,p:{hx:.3,hy:1.2,hinge:8,RF:{fx:.48,fy:.45},LF:{fx:.1,fy:.43}},txt:'Über das obere Bein hochdrücken'},
  {t:.42,p:{hx:.45,hy:1.33,RF:{fx:.48,fy:.45},LF:{fx:.42,fy:.45,fz:-.1}},txt:'Oben: aufrecht auf dem Kasten'},
  {t:.52,p:{hx:.45,hy:1.33,RF:{fx:.48,fy:.45},LF:{fx:.42,fy:.45,fz:-.1}},txt:'Kontrolliert absteigen'},
  {t:.64,p:{hx:.33,hy:1.2,hinge:8,RF:{fx:.48,fy:.45},LF:{fx:.12,fy:.43}},txt:'Kontrolliert absteigen'},
  {t:.76,p:{hx:.08,hy:.9,hinge:10,RF:{fx:.48,fy:.45}},txt:'Zweiten Fuß zurückholen'},
  {t:.88,p:{hx:.02,hy:.92,RF:{fx:.2,fy:.4}},txt:'Zweiten Fuß zurückholen'}]},
{id:'bulgarische-split-kniebeuge',name:'Bulgarische Split-Kniebeuge',group:'Beine',level:'Mittel',muscles:'Vordere Oberschenkel, Po, Hüftbeuger',volume:'3 × 8 pro Bein',
 steps:['Rücken zur Bank, einen Fuß mit dem Spann hinten auf die Bank legen.','Glocke vor der Brust, der vordere Fuß steht gut einen Schritt vor der Bank.','Senkrecht absenken, bis der vordere Oberschenkel etwa parallel ist.','Über das vordere Bein hochdrücken.'],
 mistake:'Der vordere Fuß steht zu nah an der Bank, dann schiebt das Knie weit nach vorne.',
 stance:.1,kb:'twoDown',rel:{R:1,L:1},base:{R:G,L:G,hx:-.02,hy:.86,hinge:5,LF:{fx:.3},RF:{fx:-.62,fy:.47,fa:170}},period:3.2,equip:'Kettlebell, Bank',cam:{x:-.2,y:.8},props:[{x:-.8,w:.36,h:.4,d:.4}],
 keys:[{t:0,txt:'Senkrecht absenken'},{t:.45,p:{hx:-.05,hy:.5,hinge:15},txt:'Unten: vorderer Oberschenkel parallel'},{t:.55,p:{hx:-.05,hy:.5,hinge:15},txt:'Über das vordere Bein hochdrücken'}]},
{id:'hip-thrust-an-der-bank',name:'Hip Thrust an der Bank',group:'Po & hintere Kette',level:'Mittel',muscles:'Po, hintere Oberschenkel',volume:'3 × 10–12',
 steps:['Oberer Rücken liegt an der Bankkante, Füße hüftbreit am Boden.','Glocke mit beiden Händen auf den Hüften halten.','Hüfte anheben, bis der Körper von Knie bis Schulter waagerecht ist.','Oben den Po fest anspannen und langsam absenken.'],
 mistake:'Oben ins Hohlkreuz gehen. Das Kinn bleibt leicht zur Brust gezogen.',
 stance:.14,kb:'hip',rel:{R:1,L:1},base:{R:{sh:33,inw:17},L:{sh:33,inw:17},RF:{fx:.45},LF:{fx:.45}},period:3,equip:'Kettlebell, Bank',cam:{x:-.1,y:.45,R:3.6,h:1.2},props:[{x:-.72,w:.5,h:.42,d:.5}],
 keys:[{t:0,p:{hinge:-55,hy:.18},txt:'Po anspannen, Hüfte anheben'},{t:.42,p:{hinge:-90,hy:.52},txt:'Oben: Körper waagerecht'},{t:.6,p:{hinge:-90,hy:.52},txt:'Langsam absenken'}]},
{id:'bankdruecken',name:'Bankdrücken',group:'Brust',level:'Mittel',muscles:'Brust, Trizeps, vordere Schultern',volume:'3 × 8–10',
 steps:['Rückenlage auf der Bank, Füße fest am Boden.','Zwei Glocken seitlich der Brust, Unterarme senkrecht.','Beide Glocken nach oben drücken, bis die Arme gestreckt sind.','Langsam absenken, bis die Oberarme etwa auf Bankhöhe sind.'],
 mistake:'Die Ellbogen stehen im rechten Winkel zur Seite ab. Sie zeigen leicht schräg Richtung Hüfte.',
 stance:.2,kb:'rack',kbL:'rackL',rel:{R:1,L:1},base:{hinge:-90,hx:0,hy:.56,RF:{fx:.5},LF:{fx:.5}},period:3,equip:'2 Kettlebells, Bank',cam:{x:-.2,y:.6,R:3.8,h:1.4},props:[{x:-.35,w:1.1,h:.42,d:.35}],
 keys:[{t:0,p:{R:{sh:10,inw:-60,el:95},L:{sh:10,inw:-60,el:95}},txt:'Beide Glocken nach oben drücken'},{t:.42,p:{R:{sh:90},L:{sh:90}},txt:'Oben: Arme gestreckt'},{t:.55,p:{R:{sh:90},L:{sh:90}},txt:'Langsam absenken'}]},
{id:'doppeltes-ueberkopfdruecken',name:'Doppeltes Überkopfdrücken',group:'Schultern',level:'Mittel',muscles:'Schultern, Trizeps, Rumpf',volume:'3 × 6–8',
 steps:['Zwei Glocken in der Rack-Position.','Bauch und Po anspannen, Rippen über dem Becken.','Beide Glocken senkrecht nach oben drücken.','Kontrolliert zurück in die Rack-Position.'],
 mistake:'Mit zwei Glocken fällt man leichter ins Hohlkreuz. Rumpf bleibt fest.',
 stance:.13,kb:'rack',kbL:'rackL',period:3,equip:'2 Kettlebells',
 keys:[{t:0,p:{R:AP.RACK,L:AP.RACK},txt:'Beide Glocken senkrecht drücken'},{t:.4,p:{R:{sh:178},L:{sh:178}},txt:'Oben: Oberarme neben den Ohren'},{t:.55,p:{R:{sh:178},L:{sh:178}},txt:'Zurück in die Rack-Position'}]},
{id:'gorilla-row',name:'Gorilla Row',group:'Rücken',level:'Mittel',muscles:'Breiter Rückenmuskel, mittlerer Rücken, Rumpf',volume:'3 × 8 pro Seite',
 steps:['Sehr breiter Stand, zwei Glocken zwischen den Füßen.','Tief in die Hüftbeuge, Rücken flach, beide Hände an den Griffen.','Eine Glocke zur Hüfte rudern, die andere bleibt am Boden.','Absetzen und die Seite wechseln.'],
 mistake:'Der Oberkörper dreht beim Ziehen weit auf. Er bleibt parallel zum Boden.',
 stance:.3,kb:'oneHang',kbL:'oneHangL',base:{hinge:70,hx:-.15,hy:.72},period:3.6,equip:'2 Kettlebells',
 keys:[{t:0,txt:'Rechte Glocke zur Hüfte ziehen'},{t:.2,p:{R:{sh:-65,el:80}},txt:'Oben kurz halten'},{t:.3,p:{R:{sh:-65,el:80}},txt:'Absetzen'},{t:.5,txt:'Linke Glocke zur Hüfte ziehen'},{t:.7,p:{L:{sh:-65,el:80}},txt:'Oben kurz halten'},{t:.8,p:{L:{sh:-65,el:80}},txt:'Absetzen'}]},
{id:'renegade-row',name:'Renegade Row',group:'Rumpf',level:'Fortgeschritten',muscles:'Rumpf, breiter Rückenmuskel, Schultern',volume:'3 × 6 pro Seite',
 steps:['Liegestützposition mit beiden Händen an den Griffen zweier Glocken.','Füße breiter als hüftbreit, Körper gerade wie ein Brett.','Eine Glocke zur Hüfte rudern, ohne das Becken zu drehen.','Absetzen und die Seite wechseln.'],
 mistake:'Das Becken kippt zur Seite. Breiter stehen hilft, die Hüfte ruhig zu halten.',
 stance:.2,kb:'oneDown',kbL:'oneDownL',base:{hinge:55,hx:-.01,hy:.6,RF:{fx:-.75,fy:.13,fa:-55},LF:{fx:-.75,fy:.13,fa:-55}},period:3.6,equip:'2 Kettlebells',cam:{x:-.15,y:.5,R:4.2,h:1.4,az:.6},
 keys:[{t:0,txt:'Rechte Glocke zur Hüfte ziehen'},{t:.2,p:{R:{sh:-55,el:85}},txt:'Oben: Becken bleibt ruhig'},{t:.3,p:{R:{sh:-55,el:85}},txt:'Absetzen'},{t:.5,txt:'Linke Glocke zur Hüfte ziehen'},{t:.7,p:{L:{sh:-55,el:85}},txt:'Oben: Becken bleibt ruhig'},{t:.8,p:{L:{sh:-55,el:85}},txt:'Absetzen'}]},
{id:'beidseitiger-farmer-s-walk',name:"Beidseitiger Farmer's Walk",group:'Ganzkörper',level:'Einsteiger',muscles:'Griffkraft, Trapez, Rumpf, Beine',volume:'3 × 30–40 m',
 steps:['In jeder Hand eine Glocke neben dem Körper.','Aufrecht stehen, Schultern nach hinten unten.','Mit kleinen, zügigen Schritten gehen.','Glocken am Ende kontrolliert abstellen.'],
 mistake:'Die Schultern ziehen nach vorne. Brust bleibt offen.',
 stance:.1,kb:'oneDown',kbL:'oneDownL',base:{hy:.9,R:{inw:-6},L:{inw:-6}},period:1.2,equip:'2 Kettlebells',cam:{az:.9},
 keys:[{t:0,p:{RF:{fx:.2},LF:{fx:-.2,fy:.07,fa:-15}},txt:'Aufrecht gehen'},{t:.25,p:{hy:.92,LF:{fy:.13}},txt:'Aufrecht gehen'},{t:.5,p:{RF:{fx:-.2,fy:.07,fa:-15},LF:{fx:.2}},txt:'Schultern bleiben hinten'},{t:.75,p:{hy:.92,RF:{fy:.13}},txt:'Schultern bleiben hinten'}]}
);
const AP3={PTM:{sh:-88,inw:34,el:105,rot:16},WCLR:{sh:-9,inw:10,el:51,rot:-8},WCLL:{sh:-10,inw:26,el:43,rot:-4},WCHR:{sh:116,inw:40,el:33,rot:-13},WCHL:{sh:108,inw:-6,el:47,rot:2},PTU:{sh:-23,inw:61,el:1,rot:-39},PTS:{sh:-88,inw:-34,el:105,rot:-16}};
Object.assign(AP,AP3);
const SUPK=Object.assign({},SUP,{RF:{fx:.45},LF:{fx:.45}});
const UP2={sh:180,inw:17.8};
EX.push(
{id:'kettlebell-crunch',name:'Kettlebell Crunch',group:'Bauch',level:'Einsteiger',muscles:'Gerader Bauchmuskel, vor allem oberer Teil',volume:'3 × 12–15',
 steps:['Rückenlage, Knie gebeugt, Füße am Boden.','Glocke mit beiden Händen und gestreckten Armen über der Brust halten.','Bauch anspannen und die Schultern vom Boden heben, die Glocke zeigt zur Decke.','Kurz halten und langsam ablegen.'],
 mistake:'Mit dem Kopf nach vorne ziehen. Der Blick geht schräg nach oben, das Kinn bleibt locker.',
 stance:.12,kb:'two',base:Object.assign({},SUPK,{R:UP2,L:UP2}),period:2.4,cam:FLOORCAM,
 keys:[{t:0,txt:'Schultern vom Boden heben'},{t:.42,p:{hinge:-65},txt:'Oben: Glocke zeigt zur Decke'},{t:.55,p:{hinge:-65},txt:'Langsam ablegen'}]},
{id:'ueberkopf-sit-up',name:'Überkopf-Sit-up',group:'Bauch',level:'Mittel',muscles:'Gerader Bauch, Hüftbeuger, Schulterstabilität',volume:'3 × 8–10',
 steps:['Rückenlage, Knie gebeugt, Glocke mit gestreckten Armen über der Brust.','Bauch vorspannen und Wirbel für Wirbel aufrollen.','Bis zum aufrechten Sitz hochkommen, die Glocke bleibt senkrecht über dem Kopf.','Kontrolliert zurückrollen.'],
 mistake:'Mit Schwung hochreißen. Die Bewegung ist langsam und die Arme bleiben senkrecht.',
 stance:.12,kb:'two',base:Object.assign({},SUPK,{R:UP2,L:UP2}),period:3.6,cam:FLOORCAM,
 keys:[{t:0,txt:'Wirbel für Wirbel aufrollen'},{t:.42,p:{hinge:-5},txt:'Oben: Glocke senkrecht über dem Kopf'},{t:.52,p:{hinge:-5},txt:'Kontrolliert zurückrollen'}]},
{id:'hollow-rock',name:'Hollow Rock',group:'Bauch',level:'Fortgeschritten',muscles:'Gerader Bauch, tiefe Bauchmuskeln',volume:'3 × 20 Sekunden',
 steps:['Rückenlage, Glocke mit gestreckten Armen über der Brust.','Schultern und gestreckte Beine anheben, der untere Rücken bleibt am Boden.','Den Körper wie eine Schaukel vor und zurück wiegen.','Die Bananenform halten, nicht einknicken.'],
 mistake:'Der untere Rücken hebt ab und der Körper knickt in der Hüfte ein.',
 stance:.08,kb:'two',legs:{R:'fk',L:'fk'},base:{hx:0,hy:.17,R:UP2,L:UP2},period:1.6,cam:FLOORCAM,
 keys:[{t:0,p:{hinge:-62,RF:{th:120,kn:0,fa:120},LF:{th:120,kn:0,fa:120}},txt:'Nach vorne wiegen'},{t:.5,p:{hinge:-78,hy:.15,RF:{th:100,kn:0,fa:100},LF:{th:100,kn:0,fa:100}},txt:'Nach hinten wiegen'}]},
{id:'beinheben',name:'Beinheben',group:'Bauch',level:'Mittel',muscles:'Unterer Bauch, Hüftbeuger',volume:'3 × 10–12',
 steps:['Rückenlage, die Glocke hinter dem Kopf mit beiden Händen festhalten.','Beine gestreckt knapp über dem Boden.','Beine bis in die Senkrechte heben.','Langsam wieder absenken, ohne den Boden zu berühren.'],
 mistake:'Der untere Rücken hohl beim Absenken. Nur so tief gehen, wie er am Boden bleibt.',
 stance:.08,kb:'two',legs:{R:'fk',L:'fk'},rel:{R:1,L:1},base:Object.assign({},SUP,{R:{sh:170,inw:17.8},L:{sh:170,inw:17.8}}),period:3,cam:FLOORCAM,
 keys:[{t:0,p:{RF:{th:98,kn:0,fa:98},LF:{th:98,kn:0,fa:98}},txt:'Beine gestreckt anheben'},{t:.42,p:{RF:{th:180,kn:0,fa:180},LF:{th:180,kn:0,fa:180}},txt:'Oben: Beine senkrecht'},{t:.52,p:{RF:{th:180,kn:0,fa:180},LF:{th:180,kn:0,fa:180}},txt:'Langsam absenken'}]},
{id:'toe-touch',name:'Toe Touch',group:'Bauch',level:'Einsteiger',muscles:'Oberer Bauch',volume:'3 × 12–15',
 steps:['Rückenlage, Beine senkrecht nach oben.','Glocke mit gestreckten Armen über der Brust.','Schultern anheben und die Glocke Richtung Füße schieben.','Langsam wieder ablegen.'],
 mistake:'Die Beine kippen Richtung Kopf. Sie bleiben senkrecht.',
 stance:.08,kb:'two',legs:{R:'fk',L:'fk'},rel:{R:1,L:1},base:Object.assign({},SUP,{R:{sh:90,inw:17.8},L:{sh:90,inw:17.8},RF:{th:180,kn:0,fa:180},LF:{th:180,kn:0,fa:180}}),period:2.4,cam:FLOORCAM,
 keys:[{t:0,txt:'Glocke Richtung Füße schieben'},{t:.42,p:{hinge:-62,R:{sh:75},L:{sh:75}},txt:'Oben: Schultern vom Boden'},{t:.55,p:{hinge:-62,R:{sh:75},L:{sh:75}},txt:'Langsam ablegen'}]},
{id:'holzhacker',name:'Holzhacker',group:'Bauch',level:'Mittel',muscles:'Schräge Bauchmuskeln, Schultern, Hüfte',volume:'3 × 10 pro Seite',
 steps:['Glocke seitlich am Griff fassen und außen neben ein Knie führen.','Leicht in die Knie gehen, Oberkörper dreht zur Glocke.','Die Glocke diagonal über die gegenüberliegende Schulter nach oben ziehen.','Kontrolliert zurück nach unten, dann Seite wechseln.'],
 mistake:'Die Hüfte dreht voll mit. Die Drehung kommt aus dem Oberkörper, das Becken bleibt ruhig.',
 stance:.14,kb:'two',period:2.6,cam:{az:1.0},
 keys:[{t:0,p:{hinge:40,hx:-.15,hy:.72,tw:-30,R:AP.WCLR,L:AP.WCLL},txt:'Diagonal nach oben ziehen'},{t:.5,p:{tw:35,R:AP.WCHR,L:AP.WCHL},txt:'Kontrolliert zurück nach unten'}]},
{id:'plank-pull-through',name:'Plank Pull-Through',group:'Bauch',level:'Mittel',muscles:'Tiefe Bauchmuskeln, schräge Bauchmuskeln, Schultern',volume:'3 × 8 pro Seite',
 steps:['Liegestützposition, die Glocke steht seitlich neben der Hand.','Mit der anderen Hand unter dem Körper hindurchgreifen.','Die Glocke auf die andere Seite ziehen, ohne die Hüfte zu drehen.','Hand zurücksetzen und mit der anderen Hand zurückziehen.'],
 mistake:'Die Hüfte schwankt oder geht nach oben. Füße breiter stellen und den Körper gerade halten.',
 stance:.2,kb:'floor',base:{hinge:62.6,hx:0,hy:.37,kbx:.32,RF:{fx:-.78,fy:.15,fa:-60},LF:{fx:-.78,fy:.15,fa:-60}},period:5,cam:{x:-.1,y:.4,R:4,h:1.3,az:.7},
 keys:[{t:0,p:{kbz:.4},txt:'Linke Hand greift unter dem Körper durch'},{t:.15,p:{kbz:.4,kbfL:1,L:AP.PTU},txt:'Glocke nach links ziehen'},{t:.25,p:{kbz:0,kbfL:1,L:AP.PTM},txt:'Glocke nach links ziehen'},{t:.35,p:{kbz:-.4,kbfL:1,L:AP.PTS},txt:'Hand zurücksetzen'},{t:.45,p:{kbz:-.4},txt:'Rechte Hand greift unter dem Körper durch'},{t:.6,p:{kbz:-.4,kbfR:1,R:AP.PTU},txt:'Glocke nach rechts ziehen'},{t:.7,p:{kbz:0,kbfR:1,R:AP.PTM},txt:'Glocke nach rechts ziehen'},{t:.8,p:{kbz:.4,kbfR:1,R:AP.PTS},txt:'Hand zurücksetzen'},{t:.9,p:{kbz:.4},txt:'Körper bleibt gerade'}]},
{id:'ueberkopf-kniehub',name:'Überkopf-Kniehub',group:'Bauch',level:'Einsteiger',muscles:'Unterer Bauch, Hüftbeuger, Schulterstabilität',volume:'3 × 8 pro Seite',
 steps:['Glocke mit gestrecktem Arm über Kopf halten.','Aufrecht stehen, Bauch fest.','Ein Knie bis über Hüfthöhe anheben.','Absetzen und das andere Knie heben.'],
 mistake:'Der Oberkörper lehnt sich zurück, um das Knie höher zu bringen.',
 stance:.1,kb:'rack',base:{R:{sh:180},L:{sh:10,inw:-20,el:10}},period:2.4,
 keys:[{t:0,txt:'Rechtes Knie anheben'},{t:.2,p:{RF:{fx:.3,fy:.55}},txt:'Oben kurz halten'},{t:.3,p:{RF:{fx:.3,fy:.55}},txt:'Absetzen'},{t:.5,txt:'Linkes Knie anheben'},{t:.7,p:{LF:{fx:.3,fy:.55}},txt:'Oben kurz halten'},{t:.8,p:{LF:{fx:.3,fy:.55}},txt:'Absetzen'}]}
);


EX.forEach(e=>{e.type=e.type||'kettlebell';if(e.kbCount==null)e.kbCount=e.type==='kettlebell'?(e.kbL?2:1):0;});
